### ISSUE TITLE
Springsandwich not in maven central

### ISSUE THREAD

**Issue by brennydoogles** [arikast/springsandwich#1]
Springsandwich is a great library, and adding a dependency to it in a local development environment is fairly simple. However, adding a dependency to Springsandwich in a way which allows for the project to be built via Continuous Integration or Heroku is more complicated. Adding Springsandwich to maven central would simplify both local and CI/Cloud setup.

Instructions for deploying to Maven Central can be found at https://maven.apache.org/guides/mini/guide-central-repository-upload.html

(Also note http://central.sonatype.org/pages/ossrh-guide.html)

**Comment by jromero** [comment]
A short term solution could be to add details to use jitpack.io. Such as https://jitpack.io/#arikast/springsandwich/-SNAPSHOT

**Comment by CyborgMaster** [comment]
I would love to use this from Maven Central.  That's my main blocker to including it in my project.

Edit: I've tried jitpack.io, as suggested by @jromero.  It's really cool!  I've never heard of it before, but it works great.

**Comment by arikast** [comment]
Thanks for the suggestion, finally got it on maven central!  See latest readme for a copy/paste dependency to use.
